import "./globals.css";
import { Inter } from "next/font/google";
import HomeNavBar from "@/components/navBar/page";
import { Providers } from "./providers";
import HomeFooter from "@/components/homeFooter/page";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Next - Auth ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <HomeNavBar />
          {children}
          <HomeFooter />
        </Providers>
      </body>
    </html>
  );
}
